INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1,"Diversey Gardens", "housing", 10000, "05/15/21", "02/15/25");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "Lincoln Park Playground", "playground", 4000, "03/15/21", "06/15/27");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Quann Gardens", "garden", 6000, "06/15/21", "08/15/22");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "Lula's", "restaurant", 20000, "08/15/21", "09/15/22");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "The Gap", "store", 30000, "11/15/21", "05/15/23");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Bike Path", "bike path", 50000, "01/15/21", "03/15/29");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Race for the Cure", "race", 1000, "05/15/21", "09/15/21");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Carnival", "fundraiser", 7000, "09/15/21", "06/15/24");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "Red Dress", "gala", 11000, "04/15/21", "11/15/21");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "Coats for Kids", "coat drive", 300, "02/15/21", "03/15/21");

INSERT INTO users (id, name, age) VALUES (1, "Alexandra", 28);
INSERT INTO users (id, name, age) VALUES (2, "Subbu", 27);
INSERT INTO users (id, name, age) VALUES (3, "Ronnie", 35);
INSERT INTO users (id, name, age) VALUES (4, "Dani", 45);
INSERT INTO users (id, name, age) VALUES (5, "Ally", 55);
INSERT INTO users (id, name, age) VALUES (6, "Sophie", 65);
INSERT INTO users (id, name, age) VALUES (7, "Anna", 75);
INSERT INTO users (id, name, age) VALUES (8, "Kyla", 85);
INSERT INTO users (id, name, age) VALUES (9, "Kyle", 29);
INSERT INTO users (id, name, age) VALUES (10, "Johnny", 32);
INSERT INTO users (id, name, age) VALUES (11, "Jessica", 47);
INSERT INTO users (id, name, age) VALUES (12, "Lindsey", 58);
INSERT INTO users (id, name, age) VALUES (13, "Karina", 44);
INSERT INTO users (id, name, age) VALUES (14, "Laura", 69);
INSERT INTO users (id, name, age) VALUES (15, "Rosie", 72);
INSERT INTO users (id, name, age) VALUES (16, "John", 18);
INSERT INTO users (id, name, age) VALUES (17, "Max", 32);
INSERT INTO users (id, name, age) VALUES (18, "Annie", 43);
INSERT INTO users (id, name, age) VALUES (19, "Adam", 54);
INSERT INTO users (id, name, age) VALUES (20, "Nico", 59);

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 100, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 10, 2, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 500, 3, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 200, 4, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 50, 5, 7);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 60, 6, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 75, 7, 9);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 150, 8, 9);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 170, 9, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 230, 10, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 50, 11, 5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 100, 12, 4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 1000, 13, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 40, 14, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 20, 15, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 25, 16, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 15, 17, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 30, 18, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 400, 19, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 700, 11, 4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 900, 12, 5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 10, 13, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 5, 14, 7);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 15, 15, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 90, 16, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 100, 20, 10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 300, 1, 10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 100, 4, 9);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 50, 9, 9);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 75, 9, 8);


